global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@x0tta6bl4.local'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'
  routes:
  - match:
      severity: critical
    receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: 'admin@x0tta6bl4.local'