version: '3.8'

services:
  # Prometheus - сбор метрик
  prometheus:
    image: prom/prometheus:latest
    container_name: x0tta6bl4-prometheus
    ports:
      - "9092:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
      - '--query.active-query-tracker.max-size=0'
    networks:
      - x0tta6bl4-monitoring
    restart: unless-stopped

  # Alertmanager - управление алертами
  alertmanager:
    image: prom/alertmanager:latest
    container_name: x0tta6bl4-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/config.yml:ro
      - ./data/alertmanager:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    networks:
      - x0tta6bl4-monitoring
    restart: unless-stopped

  # Grafana - визуализация
  grafana:
    image: grafana/grafana:latest
    container_name: x0tta6bl4-grafana
    user: "472"
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./data/grafana:/var/lib/grafana
    networks:
      - x0tta6bl4-monitoring
    restart: unless-stopped

  # Node Exporter - системные метрики
  node-exporter:
    image: prom/node-exporter:latest
    container_name: x0tta6bl4-node-exporter
    ports:
      - "9101:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - x0tta6bl4-monitoring
    restart: unless-stopped

  # Pushgateway - для push метрик (опционально)
  pushgateway:
    image: prom/pushgateway:latest
    container_name: x0tta6bl4-pushgateway
    ports:
      - "9091:9091"
    networks:
      - x0tta6bl4-monitoring
    restart: unless-stopped

networks:
  x0tta6bl4-monitoring:
    driver: bridge
    name: x0tta6bl4-monitoring

volumes:
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/prometheus
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/grafana
  alertmanager_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/alertmanager